# NumPy/SciPyによる線形代数

In [1]:
import numpy as np

## numpyで逆行列を計算

In [2]:
a = np.array([ [3,1,1], [1,2,1], [0, -1, 1] ])

In [7]:
inv_a=np.linalg.inv(a)
print(inv_a)

[[ 0.42857143 -0.28571429 -0.14285714]
 [-0.14285714  0.42857143 -0.28571429]
 [-0.14285714  0.42857143  0.71428571]]


## numpyで一次方程式を解く

In [8]:
b = np.array([1, 2, 3])
np.linalg.solve(a, b)

array([-0.57142857, -0.14285714,  2.85714286])

## 逆行列を使って一次方程式を解く

In [10]:
inv_a.dot(b)

array([-0.57142857, -0.14285714,  2.85714286])

## LU分解を使って一次方程式を解く

In [11]:
from scipy import linalg

In [14]:
# L: 対角成分が1の下三角行列、U: 上三角行列
lu, p = linalg.lu_factor(a)
linalg.lu_solve((lu,p), b)

array([-0.57142857, -0.14285714,  2.85714286])